### ISSUE TITLE
Parsing files and constructing valid loci  

### ISSUE THREAD

**Issue by bazyliszek** [ben-laufer/DMRichR#30]
Hello Ben! Trying out your stuff. I had few issues that I have fixed (reported) but wonder about this one below ... My files from bismark_covarge are as follow:  *.cov.gz

chr9    10397   10397   100     1       0
chr9    10403   10403   100     1       0
chr9    10468   10468   100     2       0
chr9    10469   10469   100     1       0

<img width="687" alt="BEN" src="https://user-images.githubusercontent.com/5906550/74870839-b1995700-535a-11ea-93b5-b4caac33ddfe.PNG">

Cheers, Marcin

**Comment by ben-laufer** [comment]
Hi Marcin,

Thanks for trying out DMRichR and letting me know about this issue. 

I think the issue has to do with your file extensions, since it's looking for files with `*.txt.gz` but yours are `*.cov.gz`, which I believe is because you are supplying it with bismark coverage reports instead of bismark genome-wide cytosine reports.  

So, I think you need to do one more step in `bismark`, which would be the `coverage2cytosine` call. The output should be something like`*_bismark_bt2_pe.deduplicated.bismark.cov.gz.CpG_report.txt.gz`. You can read more in [this section of the Bismark docs](https://github.com/FelixKrueger/Bismark/tree/master/Docs#optional-genome-wide-cytosine-report-output). 

If you need some examples, you can look at my [CpG_Me repository](https://github.com/ben-laufer/CpG_Me), where [these lines](https://github.com/ben-laufer/CpG_Me/blob/master/Paired-end/CpG_Me_PE_switch.sh#L252) show the commands I use to generate the reports.  

Please let me know this goes and if you run into anything else. 

Best,

Ben

**Comment by bazyliszek** [comment]
Great, let me check this out @ben-laufer . I will keep you updated, if I am able to reproduce this code. Thank you, Marcin

**Comment by bazyliszek** [comment]
The solution was to give "Name" as a column name in the excel file, instead of Sample. Maybe this could be clearly stated in the text? ;-) Cheers, Marcin

**Comment by ben-laufer** [comment]
Ah, thanks for letting me know. I'll update the READ.ME to mention this more clearly too. However, the file types you showed me earlier were the bismark coverage files and not the genome-wide cytosine reports that I mentioned. Did you end up creating those files as well? The pattern matching shouldn't be detecting the wrong type of format, and I'll look deeper into this if it is. 

Here is an example of how the genome-wide cytosine reports look:

chr2	10001	+	0	0	CG	CGT
chr2	10002	-	0	0	CG	CGN
chr2	10215	+	0	0	CG	CGA

**Comment by bazyliszek** [comment]
yes, I did create new type of files. Very nice for updating READ.ME.  Thank you!
