### ISSUE TITLE
Problem in testing for blocks of differential methylation

### ISSUE THREAD

**Issue by StefaniaTuveri** [ben-laufer/DMRichR#34]
Hello, 
I am having some troubles with the function dmrseq in your code when it comes to create the blocks. It got stuck on this function for 11 hours. I tried to increase the number of cores and the number of chrsPerChunks, but this does not change the situation. Do you have any suggestions?
This is the error:

Searching for large scale blocks with at least 5000 basepairs.
Assuming the test covariate Diagnosis is a factor.
Condition: cancer vs healthy
Parallelizing using 50 workers/cores (backend: BiocParallel:MulticoreParam).
Computing on 1 chromosome(s) at a time.

Detecting candidate regions with coefficient larger than 0.05 in magnitude.
...Chromosome 1: Error in mcexit(0L) : ignoring SIGPIPE signal
Calls: dmrseq ... bploop.lapply -> .send_to -> .send_to -> <Anonymous> -> mcexit
Error in mcexit(0L) : ignoring SIGPIPE signal
Calls: dmrseq ... bploop.lapply -> .send_to -> .send_to -> <Anonymous> -> mcexit
Smoothed (0.25 min) 

Thank you for your time!

**Comment by ben-laufer** [comment]
Hi @StefaniaTuveri, thanks for trying out DMRichR and getting in touch. This does look like a problem with the parallelization. DMRichR is heavy on RAM due to the nature of dmrseq and bsseq, where for just 20 cores we need 256 GB of RAM for some larger projects, and in general each core requires a large amount of RAM. The RAM requirements depend on number of samples, coverage, and effect size. So I think the first thing to do is try with all the default settings (20 cores and not modifying the number of chrsPerChunks) and see if you run into this again. Please let me know how that goes and if it doesn't work could you also let me know the number of samples and their coverage? Sometimes with fewer samples it goes quicker with less cores than with more.

**Comment by StefaniaTuveri** [comment]
Thank you very much for your reply. I will let you know how it will go. 
They are 4 samples with a mean coverage of 8x.
