### ISSUE TITLE
Error selecting significant DMRs: "Error in beta/pi : non-numeric argument to binary operator"

### ISSUE THREAD

**Issue by semenko** [ben-laufer/DMRichR#56]
Hey, ran into this bug with a job -- after finishing testing for DMRs with dmrseq (about 10 days of runtime :/ ), the execution crashes and run isn't saved.

Running DMRichR 1.7.1 in R 4.0.5.

Here's the crash:

<pre>
...
* 8 out of 8 permutations completed (344616 null candidates)
Selecting significant DMRs...
Error in beta/pi : non-numeric argument to binary operator
Calls: <Anonymous> ... mutate.Ranges -> mutate_rng -> overscope_eval_update -> eval_tidy
In addition: Warning messages:
1: In parallel::mccollect(wait = FALSE, timeout = 1) :
  1 parallel job did not deliver a result
2: In parallel::mccollect(wait = TRUE) :
  9 parallel jobs did not deliver results
Execution halted
</pre>

**Comment by ben-laufer** [comment]
Hi @semenko, there's a few possible explanations for this one. Would you mind sending the complete stdout and stderr logs for the run?

**Comment by semenko** [comment]
Thanks! Actually looks like this was on R 4.0.5.

Here's the entire run w/ data: https://wustl.box.com/v/dmrichr-issue-56

Log here: https://wustl.app.box.com/v/dmrichr-issue-56/file/827346674007

Command:
<pre>
$ ~/DMRichR/exec/DM.R --genome mm10 --coverage 10 --minCpGs 5 --maxPerms 8 --maxBlockPerms 8 --cutoff '0.1' --testCovariate Diagnosis --sexCheck FALSE --EnsDb FALSE --cores 24 --GOfuncR TRUE --cellComposition FALSE
</pre>

Ran on this image: https://hub.docker.com/repository/docker/semenkowustl/r_with_xml/ (on rocker/tidyverse:4.0.5)


As a semi-related issue, I'm not sure why my runtimes are so long or if this is expected for dmrseq. I'd love if the .Rdata were saved a little earlier (before potential crashers) so I could resume/debug (i.e. without the 10 day wait here).

**Comment by ben-laufer** [comment]
I had a look over the logs and the problems are related to the design. DMRichR::DM.R() is specifically made only for pairwise comparisons but you have 4 groups in your testCovariate.  I think this explains the high resource use, since a pairwise comparison with 8 samples would run quickly (even on a laptop/desktop) with DMRichR.  dmrseq itself does support more complex designs, but you'd have to talk to the dmrseq developer about the timing issues.

You could run the upstream and downstream DMRichR functions in isolation in your own workflow (and not through DM.R). This would require you to modify and exclude some DMRichR functions. However, an easier workaround for this problem would be to run all your pairwise contrasts of interest separately and then leverage them in downstream meta-analyses (see this repo and associated manuscript for some specific examples: https://github.com/ben-laufer/PEBBLES-Manuscript)

**Comment by semenko** [comment]
Ah, fascinating -- thanks so much!
