### ISSUE TITLE
cavPor genome

### ISSUE THREAD

**Issue by farmohh** [ben-laufer/DMRichR#63]
Dear Ben,

Thank you very much for the great package. 
I would like to use DMRichR for Guinea pig RRBS dataset, however I can not find the genome in BSgenome database. I was wondering if there is a way to add the cavPor3 genome to DMRichR?
Thank you!

**Comment by ben-laufer** [comment]
Hi @farmohh, since cavPor3 isn't listed in `BSgenome::available.genomes()` you will have to create your own BSgenome. [Here's an example of how to do that](https://www.bioconductor.org/packages/devel/bioc/vignettes/BSgenome/inst/doc/BSgenomeForge.pdf). You will also need need to create TxDb and org.db annotation databases [(see here for details)](https://www.bioconductor.org/packages/release/workflows/vignettes/annotation/inst/doc/Annotation_Resources.html). Then after that, you can add them into a customized version of the [`DMRichR::annotationDatabases()`](https://github.com/ben-laufer/DMRichR/blob/master/R/annotationDatabases.R).
 
If you only need DMRs, a quicker/easier approach that doesn’t require the annotation resources is to just use `DMRichR::processBismark()` or `bsseq::read.bismark()` to create bsseq objects for `dmrseq::dmrseq()`.

**Comment by farmohh** [comment]
Hi Ben,

Thank you for your response and help. I created my BSgenome and TxDb objects. However I get an error using DMRichR::processBismark() and I post the error as another issue. I would apprecite any help.
