### ISSUE TITLE
help for DMRrichR

### ISSUE THREAD

**Issue by hmyh1202** [ben-laufer/DMRichR#67]
Hi, ben:  
 In the R package of DMRrichR, it did not define parameter of compare direction.  How the R package defiine the direction of difference combination of the output ?

Thank you！

**Comment by ben-laufer** [comment]
The documentation covers this one, here's the part of interest:  "In terms of the testCovariate label (i.e. Group or Diagnosis), it is important to have the label for the experimental samples start with a letter in the alphabet that comes after the one used for control samples in order to obtain results for experimental vs. control rather than control vs. experimental."
